### ISSUE TITLE
package ‘hydroMap’ is not available (for R version 4.0.0)

### ISSUE THREAD

**Issue by emilymistick** [USGS-R/hydroMap#21]
When I try to install using the recommended code (copied below), I get this error. Any advice?

`install.packages("hydroMap", 
    repos = c("http://owi.usgs.gov/R", "http://cran.us.r-project.org"))`

Warning in install.packages :
  package ‘hydroMap’ is not available (for R version 4.0.0)

**Comment by ldecicco-USGS** [comment]
Sorry about that! We're slowly ramping down support of the owi repo. It's still possible to install this package though using the "remotes" package. Once you've installed that package, run:
```r
remotes::install_github("USGS-R/hydroMap")
```
