### ISSUE TITLE
Re-write readme

### ISSUE THREAD

**Issue by ldecicco-USGS** [USGS-R/hydroMap#23]
@dblodgett-usgs  do you see anything in the readme that:
https://usgs-r.github.io/nhdplusTools/articles/plot_nhdplus.html
can't do? I want to maybe archive/get rid of this package but have a good alternative

**Comment by dblodgett-usgs** [comment]
I wrote the nhdplusTools to use base R -- not Leaflet. Other than that, it is functionally covered.
